name: Playwright Tests  # Name of the workflow

on:  
  push:  # Run tests on push
    branches:
      - main  # Change this to match your branch
  pull_request:  # Run tests on pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu
    timeout-minutes: 10  # Prevents long-running jobs

    steps:
      - name: Checkout code  # Step 1: Get repository code
        uses: actions/checkout@v4

      - name: Setup Node.js  # Step 2: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies  # Step 3: Install npm packages
        run: npm install
      
      - name: Install http-server   # Step 4: Install Http-server
        run: npm install -g http-server
      
      - name: Install monocart Reporter
        run: npm list monocart-reporter || npm install --save-dev monocart-reporter

      - name: Install Playwright Browsers  # Step 4: Install browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests  # Step 5: Execute tests
        run: npx playwright test

      - name: Upload Playwright Report  # Step 6: Upload test report
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
